name: content-directory-schemas
on: [pull_request, push]

jobs:
  schemas_checks:
    name: Checks
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: validate
      run: |
        yarn install --frozen-lockfile
        yarn workspace @joystream/types build
        yarn workspace @joystream/cd-schemas generate:all
        yarn workspace @joystream/cd-schemas build
        yarn workspace @joystream/cd-schemas checks --quiet
